### ISSUE TITLE
Overflow with larger backend login images

### ISSUE THREAD

**Issue by PureDude** [codesource/typo3-cdsrc_bepwreset#24]
Hello everybody,
due to the link wrap in the backend login image, the following style cannot be applied to the backend-login image. This causes an overflow with larger backend login images...

`
.typo3-login-logo > img {
    display: block;
    max-width: 100%;
    height: auto;
    margin: 0 auto;
}
`

**Comment by codesource** [comment]
I am not sure to see the problem.
 
Can you attach a print-screen or an exemple?

**Comment by PureDude** [comment]
The CSS style to prevent the overflow can only be applied directly to the img - child element:
```css
/* CSS style from typo3 core: backend.css */
.typo3-login-logo > img {
    display: block;
    max-width: 100%;
    height: auto;
    margin: 0 auto;
}
```
The link wrap prevents this:
```html
<!-- Fluid template: cdsrc_bepwreset\Resources\Private\Layouts\Login.html -->
<div class="typo3-login-logo">
    <a href="" id="t3js-login-url" data-referrer-check-enabled="0">
        <img src="overflow.png" class="typo3-login-image" alt="">
    </a>
</div>
```
Result with larger backend images:
![BE-LoginScreenshot](https://user-images.githubusercontent.com/7263587/85370467-0dedcc80-b52f-11ea-9386-be0a18125939.png)
